# This is a basic workflow to help you get started with Actions

name: Dev deployment from Github to AWS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2.4.0

      
      - name: Login to DockerHub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t cygnetops/react-test -f Dockerfile.dev .
      
      - name: Build Resources  
        run: docker run -e CI=true cygnetops/react-test npm test
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
        
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-frontend-demo
          environment_name: Dockerfrontenddemo-env
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy.zip
